### ISSUE TITLE
Add a description of what this repo is to the readme

### ISSUE THREAD

**Issue by gbowerman** [Azure/fta-aas#110]
The readme does not explain what FTA is, what fta-aas is, what problem it is solving, who can or should use it, and why.
Would love to see a paragraph at the top of the readme that introduces this project and shares the scope, use cases etc.
Thanks

**Comment by flavienbwk** [comment]
Totally agree. Was going to post the same comment. This repo deserves better documentation.

**Comment by jomacedo** [comment]
Hello! FTA is Fast Track for Azure (https://azure.microsoft.com/en-us/pricing/offers/azure-fasttrack).

**Comment by jomacedo** [comment]
Noted, and fixed. Thanks for the suggestion!
