### ISSUE TITLE
As a developer I want telemetry for my application, so I can see how users interact with the application.

### ISSUE THREAD

**Issue by felipmiguel** [Azure/fta-aas#17]
[] Add application insights dependencies in the solution

**Comment by felipmiguel** [comment]
FYI: [Application insights react plugin](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin#using-react-hooks)

**Comment by vermegi** [comment]
What do we want to track? 
- how long a user spends on filling out a checklist?
- how many partially complete checklists? 
- ...
