### ISSUE TITLE
Autosave the current checklist item would be nice (so I don't need to push save for each item)

### ISSUE THREAD

**Issue by vermegi** [Azure/fta-aas#47]
This is an important MVP feature for usability. Need to make sure that the comments & status entered for a given checklist item are not lost when the user clicks on the next item in the list.

At the very least, the UI should display a warning message something like "Would you like to save before loading the next item?"

**Comment by sdolgin** [comment]
This is an important MVP feature for usability. Need to make sure that the comments & status entered for a given checklist item are not lost when the user clicks on the next item in the list.
