### ISSUE TITLE
404 on checklist

### ISSUE THREAD

**Issue by seilorjunior** [Azure/fta-aas#78]
If you open direct the link https://ftaaasdev.z6.web.core.windows.net/checklist, you are going to get a 404 as the image

The requested content does not exist.
HttpStatusCode: 404
ErrorCode: WebContentNotFound
RequestId : c86f4a38-801e-009b-7c71-b92bab000000
TimeStamp : 2022-08-26T17:32:03.4670874Z

![image](https://user-images.githubusercontent.com/13451867/186960448-d824e90c-f76d-44cd-947e-3865b5da15e0.png)

**Comment by jomacedo** [comment]
Should be working now.
